### ISSUE TITLE
cargo raze fails with "Error: invalid type: map, expected a string for key `raze`"

### ISSUE THREAD

**Issue by lgo** [google/cargo-raze#215]
While setting up a new project to use cargo raze, I had accidentally made the `raze` entry in my `Cargo.toml` use double brackets, like so:
```
[[raze]]
workspace_path = "//cargo"
target = "x86_64-unknown-linux-gnu"
```

This causes `cargo raze` to simply fail with the message

```
$ cargo raze
Error: invalid type: map, expected a string for key `raze`
```

This was certainly not a very helpful error and took a while to eventually realize it was the `Cargo.toml` that was incorrect.

**Comment by UebelAndre** [comment]
Shouldn't this be
```toml
[raze]
workspace_path = "//cargo"
target = "x86_64-unknown-linux-gnu"
```
?
