### ISSUE TITLE
cargo: unused manifest key; use package metadata?

### ISSUE THREAD

**Issue by wchargin** [google/cargo-raze#273]
When I extend my `Cargo.toml` with

```toml
[raze]
workspace_path = "//third_party/rust"
genmode = "Remote"
```

per the documentation, `cargo raze` works great! But all `cargo`
commands also now print a warning about the `raze` key:

```
$ cargo check
warning: unused manifest key: raze
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
```

[The Cargo docs mention that “tools which would like to store package
configuration in `Cargo.toml`” can use the `package.metadata` table to
ignore that warning.][d] I think that this would just amount to changing
the table from `[raze]` to `[package.metadata.raze]`:

```toml
[package.metadata.raze]
workspace_path = "//third_party/rust"
genmode = "Remote"
```

When I do so, Cargo indeed no longer complains, but now `cargo-raze`
can’t find my configuration:

```
$ cargo raze
Error: Raze failed with cause: "missing field `raze` at line 20 column 1"
```

Perhaps `cargo-raze` could be modified to accept `package.metadata.raze`
as well as `raze`, and then maybe to drop support for bare `raze` at
such a time when that breaking change would be considered acceptable?

[d]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table
