### ISSUE TITLE
How to combine features, platform and dependencies ?

### ISSUE THREAD

**Issue by davidB** [google/cargo-raze#326]
Hi,

I used crates where the same dependencies is defined with different "feature" for different target platform.
 eg in `Cargo.toml` of [bevy_winit](https://github.com/bevyengine/bevy/blob/master/crates/bevy_winit/Cargo.toml)

```toml
[features]
wayland = ["winit/wayland"]
x11 = ["winit/x11"]

[dependencies]
# bevy
bevy_app = { path = "../bevy_app", version = "0.4.0" }
bevy_ecs = { path = "../bevy_ecs", version = "0.4.0" }
bevy_input = { path = "../bevy_input", version = "0.4.0" }
bevy_math = { path = "../bevy_math", version = "0.4.0" }
bevy_window = { path = "../bevy_window", version = "0.4.0" }
bevy_utils = { path = "../bevy_utils", version = "0.4.0" }

# other
winit = { version = "0.24.0", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = { version = "0.24.0", features = ["web-sys"], default-features = false }
wasm-bindgen = { version = "0.2" }
web-sys = "0.3"
```

become

```starlack
rust_library(
    name = "bevy_winit",
    srcs = glob(["**/*.rs"]),
    aliases = {
    },
    crate_features = [
    ],
    crate_root = "src/lib.rs",
    crate_type = "lib",
    data = [],
    edition = "2018",
    rustc_flags = [
        "--cap-lints=allow",
    ],
    tags = [
        "cargo-raze",
        "manual",
    ],
    version = "0.4.0",
    # buildifier: leave-alone
    deps = [
        "@raze__bevy_app__0_4_0//:bevy_app",
        "@raze__bevy_ecs__0_4_0//:bevy_ecs",
        "@raze__bevy_input__0_4_0//:bevy_input",
        "@raze__bevy_math__0_4_0//:bevy_math",
        "@raze__bevy_utils__0_4_0//:bevy_utils",
        "@raze__bevy_window__0_4_0//:bevy_window",
        "@raze__winit__0_24_0//:winit",
    ] + selects.with_or({
        # cfg(target_arch = "wasm32")
        (
            "@io_bazel_rules_rust//rust/platform:wasm32-unknown-unknown",
            "@io_bazel_rules_rust//rust/platform:wasm32-wasi",
        ): [
            "@raze__wasm_bindgen__0_2_68//:wasm_bindgen",
            "@raze__web_sys__0_3_45//:web_sys",
            "@raze__winit__0_24_0//:winit",
        ],
        "//conditions:default": [],
    }),
)
```

So it failed because:
- on bazel side because winit is listed twice:

    ```sh
    ERROR: /home/david/.cache/bazel/_bazel_david/1570ea1cacebfda74002c263f99cf611/external/raze__bevy_winit__0_4_0/BUILD.bazel:33:13: Label '@raze__winit__0_24_0//:winit' is duplicated in the 'deps' attribute of rule 'bevy_winit'
    ```

- on runtime (I guess because expected features will not be enabled)

If anyone have a immediate solution, please share. Else I would like to know/discuss how this kind of behavior could be translated into bazel (and later implemented into cargo-raze, I could try to make a PR) ?

- idea: adding some kind of `select` into the generation of `crate_features`  ?
