### ISSUE TITLE
Unable to access binary-only crate refinery-cli

### ISSUE THREAD

**Issue by rahulmutt** [google/cargo-raze#391]
I'm trying to get access to the binary only crate `refinery-cli`:

```toml
# Cargo.toml

[dependencies]
refinery_cli = "0.5.0"

[package.metadata.raze.crates.refinery_cli.'0.5.0']
extra_aliased_targets = [
    "cargon_bin_refinery"
]
```
And `cargo raze` gives me:
```
Found unused raze crate settings for `refinery_cli`
```

I also observed that there is no generated build file for `refinery-cli` anywhere in the `cargo/remote` folder. There was another create that contained both library & binaries (`aeron-rs`) and I was able to successfully access the binary from that one, so I wonder if fact that it is a binary-only crate is messing up raze's resolution somehow.

**Comment by rahulmutt** [comment]
I was able to resolve the issue with the following entries in `Cargo.toml`:

```toml
[package.metadata.raze.binary_deps]
refinery_cli = { version = "0.5.0", features = ["postgresql"] }

[package.metadata.raze.crates.refinery_cli.'0.5.0']
extra_aliased_targets = [
    "cargo_bin_refinery"
]
```
