### ISSUE TITLE
Reimplement what cargo does to detect bad renames

### ISSUE THREAD

**Issue by sayrer** [google/cargo-raze#424]
As surfaced in #282.

The problem manifests from this:

```toml
[dependencies]
bytes_new = { version = "0.3.0", package = "bytes" }
bytes_old = { version = "0.3.0", package = "bytes" }
```

Strictly this is an error. Right now cargo metadata will basically lose both bytes deps
from the resolve graph :gruntle: but a cargo build will scream about having the same basic
package with multiple names.

Currently there is no good solution using metadata.
