### ISSUE TITLE
could not clone raze binary_deps from git

### ISSUE THREAD

**Issue by weixiao-huang** [google/cargo-raze#446]
I want to generate BUILD files for a binary crate ONLY from git instead of crate.io, so I specify binary_deps below:

```toml
[package.metadata.raze.binary_deps]
kata-agent = { git = "https://github.com/kata-containers/kata-containers.git", tag = "2.1.0", version = "0.1.0"}
```

However, when I exec `cargo raze -v`, I got error below

```
Error: Package `kata-agent` not found on crates.io.
```

So how should I generate the binary_deps from git repository?
